name: Reusable deploy
on: workflow_call
jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo '${{ needs.build.outputs.script-file }}'
      - name: Deploy code
        run: echo "Deploying..."